slurm_config: big
task_type: local_predict
dataset:
  split: test
  video_processor: YoucookVideoProcessor
  aligner: DSAligner
  bert_name: bert-base-uncased
  meta_processor: YoucookMetaProcessor
  test_path: /var/scratch/pbagad/datasets/howto100m_metadata_eval/youcook_val.pkl
  trainval_annotation: /var/scratch/pbagad/datasets/youcook2/annotations/youcookii_annotations_trainval.json
  use_annotation_text: true
  vfeat_dir: /var/scratch/pbagad/datasets/youcook2/feat/feat_how2_s3d/validation/
  text_processor: TextProcessor
  num_iso_layer: 12
  max_video_len: 32
  max_len: 96
fairseq:
  dataset:
    batch_size: 256
    valid_subset: test
    num_workers: 2
  common_eval:
    path: /var/scratch/pbagad/projects/Test-of-Time-dev/external/requirements/fairseq/runs/retri/videoclip/checkpoint_best.pt
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 6
eval:
  save_path: runs/retri/videoclip/youcook_zs/eval
metric: RetrievalMetric
predictor: RetrievalPredictor
